INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ajani Goldmane", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ajani's Pridemate", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Angelic Arbiter", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Armored Ascension", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Baneslayer Angel", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Celestial Purge", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Condemn", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Day of Judgment", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elite Vanguard", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Honor of the Pure", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Knight Exemplar", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leyline of Sanctity", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Roc Egg", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Serra Angel", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Serra Ascendant", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Silence", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sun Titan", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vengeful Archon", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("War Priest of Thune", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("White Knight", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Air Servant", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Alluring Siren", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Call to Mind", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Clone", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Conundrum Sphinx", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Flashfreeze", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Frost Titan", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jace Beleren", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jace's Ingenuity", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leyline of Anticipation", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mass Polymorph", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Merfolk Sovereign", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mind Control", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Redirect", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sleep", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stormtide Leviathan", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Time Reversal", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Traumatize", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wall of Frost", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Water Servant", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Black Knight", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Captivating Vampire", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Corrupt", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dark Tutelage", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Deathmark", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Demon of Death's Gate", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Diabolic Tutor", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grave Titan", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Haunting Echoes", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Howling Banshee", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leyline of the Void", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Liliana Vess", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Liliana's Caress", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Nantuko Shade", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Necrotic Plague", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phylactery Lich", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reassembling Skeleton", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Relentless Rats", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rise from the Grave", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Royal Assassin", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ancient Hellkite", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chandra Nalaar", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chandra's Spitfire", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Combust", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cyclops Gladiator", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Destructive Force", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Earth Servant", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ember Hauler", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fire Servant", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fireball", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Goblin Chieftain", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hoarding Dragon", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Inferno Titan", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leyline of Punishment", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Magma Phoenix", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Prodigal Pyromancer", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Pyroclasm", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reverberate", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shiv's Embrace", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wild Evocation", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Acidic Slime", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Autumn's Veil", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Awakener Druid", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Back to Nature", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Birds of Paradise", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cudgel Troll", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Duskdale Wurm", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elvish Archdruid", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fauna Shaman", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gaea's Revenge", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Garruk Wildspeaker", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Garruk's Packleader", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leyline of Vitality", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mitotic Slime", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Nature's Spiral", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Obstinate Baloth", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Overwhelming Stampede", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Primeval Titan", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Prized Unicorn", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Protean Hydra", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Angel's Feather", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Brittle Effigy", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Crystal Ball", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Demon's Horn", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dragon's Claw", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elixir of Immortality", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gargoyle Sentinel", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jinxed Idol", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Juggernaut", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kraken's Eye", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ornithopter", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Platinum Angel", "Mythic Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sorcerer's Strongbox", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Steel Overseer", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stone Golem", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sword of Vengeance", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Temple Bell", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Triskelion", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Voltaic Key", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Warlord's Axe", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Whispersilk Cloak", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wurm's Tooth", "Uncommon", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dragonskull Summit", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Drowned Catacomb", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Glacial Fortress", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mystifying Maze", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rootbound Crag", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sunpetal Grove", "Rare", "Magic 2011");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Abuna Acolyte", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Auriok Edgewright", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dispense Justice", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elspeth Tirel", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Glimmerpoint Stag", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Indomitable Archangel", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kemba, Kha Regent", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leonin Arbiter", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myrsmith", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Razor Hippogriff", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sunblast Angel", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tempered Steel", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("True Conviction", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vigil for the Lost", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Argent Sphinx", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darkslick Drake", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dissipation Field", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grand Architect", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Halt Order", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Inexorable Tide", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Quicksilver Gargantuan", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Riddlesmith", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shape Anew", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Thrummingbird", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trinket Mage", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Twisted Image", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Volition Reins", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Carnifex Demon", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Corrupted Harvester", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Exsanguinate", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Flesh Allergy", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Geth, Lord of the Vault", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hand of the Praetors", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ichor Rats", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Memoricide", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Necrogen Scudder", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Necrotic Ooze", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Painful Quandary", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Painsmith", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skinrender", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skithiryx, the Blight Dragon", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Arc Trail", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Barrage Ogre", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bloodshot Trainee", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cerebral Eruption", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Embersmith", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Furnace Celebration", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hoard-Smelter Dragon", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Koth of the Hammer", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kuldotha Phoenix", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Molten Psyche", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ogre Geargrabber", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Oxidda Scrapmelter", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spikeshot Elder", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tunnel Ignus", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Acid Web Spider", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Asceticism", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bellowing Tanglewurm", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Carrion Call", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Engulfing Slagwurm", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ezuri, Renegade Leader", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ezuri's Brigade", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Genesis Wave", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Liege of the Tangle", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lifesmith", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Putrefax", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Slice in Twain", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tangle Angler", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Viridian Revel", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Venser, the Sojourner", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Argentum Armor", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Barbed Battlegear", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chimeric Mass", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Clone Shell", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Contagion Clasp", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Contagion Engine", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Culling Dais", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darksteel Axe", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darksteel Juggernaut", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darksteel Myr", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darksteel Sentinel", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Etched Champion", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Golem Artisan", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Golem's Heart", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grafted Exoskeleton", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grindclock", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Heavy Arbalest", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Infiltration Lens", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kuldotha Forgemaster", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Liquimetal Coating", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Livewire Lash", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lux Cannon", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Memnite", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mimic Vat", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mindslaver", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Molten-Tail Masticore", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mox Opal", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Battlesphere", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Galvanizer", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Propagator", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Reservoir", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Necropede", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Nim Deathmantle", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Palladium Myr", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Platinum Emperion", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Precursor Golem", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Prototype Portal", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ratchet Bomb", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rust Tick", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rusted Relic", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Semblance Anvil", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Steel Hellkite", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Strata Scythe", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sword of Body and Mind", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Throne of Geth", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tower of Calamities", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trigon of Corruption", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trigon of Infestation", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trigon of Mending", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trigon of Rage", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trigon of Thought", "Uncommon", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Venser's Journal", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wurmcoil Engine", "Mythic Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Blackcleave Cliffs", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Copperline Gorge", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darkslick Shores", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Razorverge Thicket", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Seachrome Coast", "Rare", "Scars of Mirrodin");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Accorder Paladin", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Choking Fumes", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gore Vassal", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hero of Bladehold", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kemba's Legion", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Leonin Relic-Warder", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mirran Crusader", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Rebirth", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Victory's Herald", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("White Sun's Zenith", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Blue Sun's Zenith", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Consecrated Sphinx", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Corrupted Conscience", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cryptoplasm", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Distant Memories", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mitotic Manipulation", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Neurok Commando", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Treasure Mage", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vedalken Anatomist", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vedalken Infuser", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Black Sun's Zenith", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Flesh-Eater Imp", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Go for the Throat", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gruesome Encore", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Massacre Wurm", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Nested Ghoul", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Crusader", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Vatmother", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sangromancer", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Septic Rats", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Galvanoth", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Goblin Wardriver", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hellkite Igniter", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hero of Oxid Ridge", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Into the Core", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kuldotha Flamefiend", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Metallic Mastery", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Red Sun's Zenith", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Slagstorm", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spiraling Duelist", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Creeping Corrosion", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Green Sun's Zenith", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lead the Stampede", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Melira's Keepers", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Hydra", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Plaguemaw Beast", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Praetor's Counsel", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Quilled Slagwurm", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Thrun, the Last Troll", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Viridian Corrupter", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Glissa, the Traitor", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tezzeret, Agent of Bolas", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Blightsteel Colossus", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bonehoard", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Brass Squire", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Core Prowler", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darksteel Plate", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Decimator Web", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Knowledge Pool", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lumengrid Gargoyle", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Magnetic Mine", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mirrorworks", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mortarpod", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Turbine", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Welder", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Peace Strider", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Juggernaut", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Revoker", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Pierce Strider", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Piston Sledge", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Plague Myr", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Psychosis Crawler", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shimmer Myr", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Signal Pest", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Silverskin Armor", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skinwing", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sphere of the Suns", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spine of Ish Sah", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Strandwalker", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sword of Feast and Famine", "Mythic Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Thopter Assembly", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Titan Forge", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Viridian Claw", "Uncommon", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Contested War Zone", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Inkmoth Nexus", "Rare", "Mirrodin Besieged");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Karn Liberated", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Auriok Survivors", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Blade Splicer", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cathedral Membrane", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chancellor of the Annex", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dispatch", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Due Respect", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elesh Norn, Grand Cenobite", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Exclusion Ritual", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Inquisitor Exarch", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Marrow Shards", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Master Splicer", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Norn's Annex", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Unlife", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Puresteel Paladin", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shattered Angel", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Argent Mutation", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Arm with AEther", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chancellor of the Spires", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Corrupted Resolve", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Deceiver Exarch", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jin-Gitaxias, Core Augur", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mental Misstep", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mindculling", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Ingester", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Metamorph", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Psychic Surgery", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tezzeret's Gambit", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Viral Drake", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wing Splicer", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Xenograft", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Caress of Phyrexia", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chancellor of the Dross", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Despise", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dismember", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Enslave", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Entomber Exarch", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Glistening Oil", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ichor Explosion", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Life's Finale", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Obliterator", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Postmortem Lunge", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Praetor's Grasp", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reaper of Sheoldred", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sheoldred, Whispering One", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Surgical Extraction", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Whispering Specter", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Act of Aggression", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bludgeon Brawl", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chancellor of the Forge", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fallen Ferromancer", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Geosurge", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gut Shot", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Invader Parasite", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Moltensteel Dragon", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Priest of Urabrask", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rage Extractor", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Slag Fiend", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tormentor Exarch", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Urabrask the Hidden", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vulshok Refugee", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Whipflare", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Beast Within", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Birthing Pod", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Brutalizer Exarch", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chancellor of the Tangle", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Corrosive Gale", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fresh Meat", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Greenhilt Trainee", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Melira, Sylvok Outcast", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mycosynth Fiend", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Noxious Revival", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexian Swarmlord", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spinebiter", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Triumph of the Hordes", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vital Splicer", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vorinclex, Voice of Hunger", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jor Kadeen, the Prevailer", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Alloy Myr", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Batterskull", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Caged Sun", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Conversion Chamber", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Darksteel Relic", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Etched Monstrosity", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hex Parasite", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Isolation Cell", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kiln Walker", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lashwrithe", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mindcrank", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Myr Superion", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Necropouncer", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Omen Machine", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shrine of Boundless Growth", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shrine of Burning Rage", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shrine of Limitless Power", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shrine of Loyal Legions", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Shrine of Piercing Vision", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sickleslicer", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Soul Conduit", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spellskite", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Surge Node", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sword of War and Peace", "Mythic Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Torpor Orb", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Unwinding Clock", "Rare", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phyrexia's Core", "Uncommon", "New Phyrexia");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Aegis Angel", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Alabaster Mage", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Angelic Destiny", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Arbalest Elite", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Archon of Justice", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Celestial Purge", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Day of Judgment", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elite Vanguard", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gideon Jura", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gideon's Avenger", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grand Abolisher", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Honor of the Pure", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mesa Enchantress", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Oblivion Ring", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Personal Sanctuary", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Roc Egg", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Serra Angel", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spirit Mantle", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sun Titan", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Timely Reinforcements", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Alluring Siren", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Azure Mage", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Belltower Sphinx", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Djinn of Wishes", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Flashfreeze", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Frost Titan", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jace, Memory Adept", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jace's Archivist", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Levitation", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lord of the Unreal", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Master Thief", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mind Control", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mind Unbound", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phantasmal Dragon", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Phantasmal Image", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Redirect", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sphinx of Uthuun", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Time Reversal", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Turn to Frog", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Visions of Beyond", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bloodlord of Vaasgoth", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Call to the Grave", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cemetery Reaper", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Consume Spirit", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Deathmark", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Diabolic Tutor", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grave Titan", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Monomania", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Onyx Mage", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reassembling Skeleton", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Royal Assassin", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rune-Scarred Demon", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sengir Vampire", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Smallpox", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sorin Markov", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sorin's Vengeance", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sutured Ghoul", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vampire Outcasts", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Vengeful Pharaoh", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Zombie Infestation", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chandra, the Firebrand", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Chandra's Phoenix", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Circle of Flame", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Combust", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Crimson Mage", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fireball", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Flameblast Dragon", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Furyborn Hellkite", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Goblin Bangchuckers", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Goblin Chieftain", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Goblin Grenade", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grim Lavamancer", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Inferno Titan", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Manabarbs", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reverberate", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Scrambleverse", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stormblood Berserker", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tectonic Rift", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Volcanic Dragon", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Warstorm Surge", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Acidic Slime", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Arachnus Spinner", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Autumn's Veil", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Birds of Paradise", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Carnage Wurm", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cudgel Troll", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Doubling Chant", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dungrove Elder", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elvish Archdruid", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Garruk, Primal Hunter", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Garruk's Horde", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hunter's Insight", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Jade Mage", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lure", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Overrun", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Primeval Titan", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Primordial Hydra", "Mythic Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rites of Flourishing", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skinshifter", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stingerfling Spider", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Adaptive Automaton", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Angel's Feather", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Crown of Empires", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Crumbling Colossus", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Demon's Horn", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dragon's Claw", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Druidic Satchel", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elixir of Immortality", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Greatsword", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kite Shield", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kraken's Eye", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Pentavus", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Quicksilver Amulet", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rusted Sentinel", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Scepter of Empires", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Solemn Simulacrum", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sundial of the Infinite", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Swiftfoot Boots", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Thran Golem", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Throne of Empires", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Worldslayer", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wurm's Tooth", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Buried Ruin", "Uncommon", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dragonskull Summit", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Drowned Catacomb", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Glacial Fortress", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rootbound Crag", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sunpetal Grove", "Rare", "Magic 2012");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Abattoir Ghoul", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Angel of Flight Alabaster", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Angelic Overseer", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Army of the Damned", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Back from the Brink", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Balefire Dragon", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Battleground Geist", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bitterheart Witch", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Blasphemous Act", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bloodgift Demon", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bloodline Keeper", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Boneyard Wurm", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Bramblecrush", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Burning Vengeance", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Butcher's Cleaver", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cackling Counterpart", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cellar Door", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Champion of the Parish", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Charmbreaker Devils", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Civilized Scholar", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Clifftop Retreat", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Cloistered Youth", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Creeping Renaissance", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Creepy Doll", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Curiosity", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Curse of Death's Hold", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Curse of Stalked Prey", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Curse of the Nightly Hunt", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Daybreak Ranger", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dearly Departed", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Demonmail Hauberk", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Desperate Ravings", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Devil's Play", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Diregraf Ghoul", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Disciple of Griselbrand", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Dissipate", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Divine Reckoning", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elder of Laurels", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Elite Inquisitor", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Endless Ranks of the Dead", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Essence of the Wild", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Evil Twin", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Falkenrath Marauders", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Falkenrath Noble", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Fiend Hunter", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Full Moon's Rise", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gallows Warden", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Galvanic Juggernaut", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Garruk Relentless", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gatstaf Shepherd", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gavony Township", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Geist of Saint Traft", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Geist-Honored Monk", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Geistcatcher's Rig", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ghost Quarter", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grasp of Phantoms", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Graveyard Shovel", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grimgrin, Corpse-Born", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Grimoire of the Dead", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Gutter Grime", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hamlet Captain", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hanweir Watchkeep", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Heartless Summoning", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Heretic's Punishment", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hinterland Harbor", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Hollowhenge Scavenger", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Inquisitor's Flail", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Instigator Gang", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Intangible Virtue", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Into the Maw of Hell", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Invisible Stalker", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Isolated Chapel", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kessig Cagebreakers", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kessig Wolf Run", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Kruin Outlaw", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Laboratory Maniac", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lantern Spirit", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Liliana of the Veil", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ludevic's Test Subject", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Lumberknot", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Make a Wish", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Manor Gargoyle", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mask of Avacyn", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mausoleum Guard", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mayor of Avabruck", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Memory's Journey", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mentor of the Meek", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Midnight Haunting", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mikaeus, the Lunarch", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mindshrieker", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Mirror-Mad Phantasm", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Moan of the Unhallowed", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Moldgraf Monstrosity", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Moorland Haunt", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Morkrut Banshee", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Murder of Crows", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Nephalia Drownyard", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Nevermore", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Olivia Voldaren", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Parallel Lives", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Paraselene", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Past in Flames", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Purify the Grave", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rage Thrower", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rakish Heir", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rally the Peasants", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reaper from the Abyss", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Reckless Waif", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rolling Temblor", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Rooftop Storm", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Runechanter's Pike", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Runic Repetition", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Scourge of Geier Reach", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Screeching Bat", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sever the Bloodline", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Silver-Inlaid Dagger", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skaab Goliath", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skaab Ruinator", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skirsdag Cultist", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Skirsdag High Priest", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Slayer of the Wicked", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Snapcaster Mage", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spectral Rider", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Spider Spawning", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Splinterfright", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stensia Bloodhall", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stony Silence", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Stromkirk Noble", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sturmgeist", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Sulfur Falls", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tree of Redemption", "Mythic Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Trepanation Blade", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Tribute to Hunger", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Ulvenwald Mystics", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Unbreathing Horde", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Unburial Rites", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Undead Alchemist", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Village Cannibals", "Uncommon", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Witchbane Orb", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Woodland Cemetery", "Rare", "Innistrad");
INSERT INTO Cards (name, rarity, mtgset) VALUES ("Wreath of Geists", "Uncommon", "Innistrad");
